"""Contract-driven control package for the target runtime architecture."""

from cat_follow.control.decision_engine import DecisionEngine
from cat_follow.control.fsm import FSM, TransitionResult, is_transition_allowed
from cat_follow.control.types import (
    AckStatus,
    AckType,
    CarTrackingState,
    CommandName,
    CommandState,
    DecisionInput,
    DecisionOutput,
    DecisionState,
    FSMSnapshot,
    FsmEvent,
    FsmState,
    HomeState,
    MessageType,
    NavigationState,
    OverheadState,
    RangeBackend,
    RangeState,
    ReasonCode,
    RejectionCause,
    SharedSnapshot,
    SystemState,
    TargetSource,
    TelemetryEventType,
    TelemetrySeverity,
    ThermalState,
    ThreadHealthState,
    TrackingObjectState,
    VisionState,
)

__all__ = [
    "AckStatus",
    "AckType",
    "CarTrackingState",
    "FSM",
    "TransitionResult",
    "is_transition_allowed",
    "CommandName",
    "CommandState",
    "DecisionEngine",
    "DecisionInput",
    "DecisionOutput",
    "DecisionState",
    "FSMSnapshot",
    "FsmEvent",
    "FsmState",
    "HomeState",
    "MessageType",
    "NavigationState",
    "OverheadState",
    "RangeBackend",
    "RangeState",
    "ReasonCode",
    "RejectionCause",
    "SharedSnapshot",
    "SystemState",
    "TargetSource",
    "TelemetryEventType",
    "TelemetrySeverity",
    "ThermalState",
    "ThreadHealthState",
    "TrackingObjectState",
    "VisionState",
]
